name: rspec with truffleruby

on:
  push:
    branches:    
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '46 4 * * *'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        mode: [ latency, throughput ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker image
      run: docker build -f Dockerfile-truffleruby-head -t school-experience:latest .
    - name: spin up
      run : |
        cat > .env << EOL
        RUBYOPT_SCHOOL_EXPERIENCE=--experimental-options --engine.Mode=${{matrix.mode}}
        RUBYOPT_DELAYED_JOBS=--experimental-options --engine.Mode=${{matrix.mode}}
        RUBYOPT_DB_TASKS=--experimental-options --engine.Mode=${{matrix.mode}}
        EOL
        docker-compose up -d
        WAIT_COUNT=0
        until docker-compose ps | grep -m 1 "db-tasks" | grep -m 1 "Exit 0" || [ $WAIT_COUNT -eq 48 ]; do echo "WAIT COUNT $(( WAIT_COUNT++ ))" && sleep 5 ; done
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        ref: graalvm
        repository: eregon/FlameGraph
        path: flame-graph
    - name: run a spec with profiling
      run: |
        docker-compose run \
              -e RUBYOPT='--engine.Mode=${{matrix.mode}} --experimental-options --cpusampler --cpusampler.OutputFile=/ci_build/cpusampling.json --cpusampler.SampleInternal --cpusampler.Mode=roots --cpusampler.Output=json' \
              --no-deps \
              --rm db-tasks rspec spec/controllers/schools/placement_dates/subject_selections_controller_spec.rb
        flame-graph/stackcollapse-graalvm.rb cpusampling.json | flame-graph/flamegraph.pl > cpusampling.svg
    - uses: actions/upload-artifact@v1
      with:
        name: cpusampling.svg
        path: ./cpusampling.svg
    - name: run specs
      run: docker-compose run -e RUBYOPT=--enging.Mode='${{matrix.mode}}' --no-deps --rm db-tasks rspec --format progress --format RspecJunitFormatter --out /ci_build/rspec_results.xml
